#!/usr/bin/env ruby

require('fileutils')
require('rubygems')
require('rubygems/command')
require('rubygems/commands/push_command')
require('rubygems/package')

built_gems = ::Dir::glob("**/*.gemspec").map!(&::File::method(:absolute_path)).each_with_object(::Array::new) {
  # NOTE: We must `chdir` *before* `::Gem::Spec::load` to make each spec's `::Dir::glob` work correctly.
  # I did try using `#glob`'s `base:` argument and transforming the results with `#absolute_path`,
  # but then the files get added to the built gem along with the absolute directory tree,
  # so they need to stay relative to the `gemspec`'s location.
  ::Dir::chdir(::File::absolute_path(::File::dirname(_1)))
  spec = ::Gem::Specification::load(_1)

  # Don't auto-build-and-release components mid-development.
  # `::Gem::Specification#metadata` is supported since 2.0, but keys and values must be `::String`s.
  # We don't really care what the value is — if it's set at all then it's set.
  next if spec.metadata.has_key?("experimental")

  # Collect built gems in a separate location. This should be identical for every gem in a build run,
  # since they all share a version number, but we will recompute it off of each `Specification` anyway.
  gem_dir = ::File::join(__dir__, 'gems', spec.version.to_s)
  ::FileUtils::mkdir_p(gem_dir)

  # Fix up the permissions of each spec's `#files` to avoid annoying "not world-readable" Warning.
  # Alternative to `::FileUtils`: `stat`, `mode` mask, and `chmod`: https://stackoverflow.com/a/35852139
  spec.files.each { |file| ::FileUtils::chmod('o+r', file) }

  # Do it. Do it now.
  # This will emit the normal `stdout` that `gem build <path>` would for each gem.
  # See https://github.com/rubygems/rubygems/blob/master/lib/rubygems/package.rb
  _2.append(::Gem::Package::build(spec, false, false, ::File::join(gem_dir, "#{spec.name}-#{spec.version.to_s}.gem")))
}

# Take OTP once and re-use it to avoid each iteration prompting for its own.
puts "Please enter OTP code:\t"
otp = gets.chomp

# Use our own list of built gems and avoid `::Dir::glob` to avoid the possibility of unintentional uploads
# of files mistakenly (or maliciously) left in the `gems/<version>` directory.
built_gems.each { |absolute_path|
  ::Gem::Commands::PushCommand::new.tap {
    _1.options.store(:args, [absolute_path])
    _1.options.store(:otp, otp)
  }.execute
}
