source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Depend on the DistorteD core in the same repo as us.
gem 'distorted', :path => '../DistorteD-Ruby'

gemspec
