source('https://rubygems.org')

gemspec

gem('xross-the-xoul', :path => File.join(File.dirname(__FILE__), '..', 'XROSS THE XOUL'))

# Use a local `addressable` until https://github.com/sporkmonger/addressable/pull/449is closed/released.
gem('addressable', :path => File.join(File.dirname(__FILE__), '..', '..', 'addressable'))

# "Unlike :git, bundler does not compile C extensions for gems specified as paths."
#
# Using `:git` via `bundle config local.ox ~/Works/ox`
#gem 'ox', :github => 'okeeblow/ox', :branch => 'intern_string'

# Bundler doesn't understand this Gem's GEM_STUB thing afaict, but installing it manually works:
# `bundle exec gem install ../../ruby-extattr/extattr-0.4.TRYOUT.20210911.113237.gem`
#gem 'extattr', :github => 'okeeblow/ruby-extattr', :branch => 'master'
